import Head from 'next/head'

export default function Index() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark">

      </main>

      <footer >
      </footer>
    </div>
  )
}
